import optparse
import logging
import os
import yaml
from datetime import datetime

def parse_input_file(file_path):
    # Input file is a YAML file that contains the table definition
    # The file is parsed and the table is generated
    # The table is returned as a dictionary
    with open(file_path, "r") as file:
        data = yaml.load(file, Loader=yaml.FullLoader)

    # Sanity Check - Ensure that all the set fields in the decodes are part of the output fields
    output = data["output"]
    fields = []
    for x in output:
        # Find the index of the fiels dictionary
        if "fields" in x.keys():
            fields = x["fields"]
            break
    for decode in data["decodes"]:
        for f in decode["decodes"]:
            if f not in fields:
                logger.error(f"Field {f} not found in output fields for instruction {decode['instr']}")
                exit(1)

    return data

def gen_sv_header(data):
    type_name = None
    output = data["output"]
    for x in output:
        # Find the index of the fiels dictionary
        if "type_name" in x.keys():
            type_name = x["type_name"]
            break
    header = f"// Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - DO NOT EDIT THIS FILE, REGENERATE INSTEAD\n\n"
    header += f"module {data['module_name']} (\n"
    header += f"\tinput logic [{data['input']-1}:0] i,\n"
    header += f"\toutput {type_name} o\n"
    header += f");\n\n"
    return header

def gen_sv_footer(data):
    footer = f"endmodule\n"
    return footer

def gen_sv_type_header(data):
    fields = []
    output = data["output"]
    for x in output:
        # Find the index of the fiels dictionary
        if "fields" in x.keys():
            fields = x["fields"]
            break
    for x in output:
        # Find the index of the fiels dictionary
        if "type_name" in x.keys():
            type_name = x["type_name"]
            break
    # Include guards: file is both on flists and `include`d from types.svh.
    guard = f"{type_name.upper()}_SVH"
    body = f"`ifndef {guard}\n"
    body += f"`define {guard}\n"
    body += f"typedef struct packed {{\n"
    for f in fields:
        body += f"\tlogic {f};\n"
    body += f"}} {type_name};\n"
    body += f"`endif\n"
    return body, type_name

def backend_native(data):
    fields = []
    output = data["output"]
    for x in output:
        # Find the index of the fiels dictionary
        if "fields" in x.keys():
            fields = x["fields"]
            break
    body = "\talways_comb begin\n"
    body += "\t\tcasez (i)\n"
    for decode in data["decodes"]:
        body += "\t\t\t{"
        for f in decode["match"]:
            body += "1'b1" if f == "1" else "1'b0" if f == "0" else "1'b?"
            body += ","
        # remove last comma
        body = body[:-1]
        body += "} : o = {"
        for f in fields:
            body += "1'b1" if f in decode["decodes"] else "1'b0"
            body += ","
        # remove last comma
        body = body[:-1]
        body += "}; "
        body += f"// {decode['instr']}\n"
    body += "\t\t\tdefault: o = 'b0;\n"
    body += "\t\tendcase\n\tend\n"
    return body

def backend_espresso(data):
    pass

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger()

    parser = optparse.OptionParser()
    parser.add_option("-t", "--table", dest="table", help="table to generate")
    parser.add_option(
        "-b", "--backend",
        dest="backend",
        type="choice",
        choices=["native", "espresso"],
        help="backend to use (native or espresso)"
    )
    parser.add_option("-o", "--output", dest="output", help="output folder")
    (options, args) = parser.parse_args()

    if options.table is None:
        print("Error: table is required")
        parser.print_help()
        exit(1)

    if options.backend is None:
        options.backend = "native"
        logger.warning("backend not specified, using default: native")

    if options.output is None:
        options.output = f"gen"
        logger.warning("output not specified, using default: gen")

    os.makedirs(options.output, exist_ok=True)

    data = parse_input_file(options.table)
    header = gen_sv_header(data)

    body = ""
    if options.backend == "native":
        body = backend_native(data)
    elif options.backend == "espresso":
        body = backend_espresso(data)

    footer = gen_sv_footer(data)

    with open(os.path.join(options.output, f"{data['module_name']}.sv"), "w") as file:
        file.write(header)
        file.write(body)
        file.write(footer)
        file.close()
    logger.info(f"Generated {data['module_name']}.sv")

    type_header, type_name = gen_sv_type_header(data)
    with open(os.path.join(options.output, f"{type_name}.svh"), "w") as file:
        file.write(type_header)
        file.close()
    logger.info(f"Generated {type_name}.svh")